### ISSUE TITLE
CPU detection not working

### ISSUE THREAD

**Issue by mee** [hdrie/xp-benchmark-tool#21]
https://github.com/hdrie/xp-benchmark-tool/blob/7e661cbc60279131f0878fcae5bc2b9b5598fef2/run-benchmark.ps1#L32

This was failing to detect the CPU on my system,
```
.\run-benchmark.ps1 : File C:\Applications\X-Plane 12\run-benchmark.ps1 cannot be loaded because running scripts is
disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\run-benchmark.ps1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

because in my `Log.txt`, the CPU is prefixed with "CPU Type:": `CPU type: AMD Ryzen 7 9800X3D 8-Core Processor - Speed: 4.4-4.8 GHz - Cores: 16`

I think this should either use the system collection method described in the comment, or change this regex to the following.
```
$cpuRegex='CPU (?:0|type): (.+)\s+Speed.+'
```

I tested the above regex change and saw this in my `ZZ_BenchResults.txt`: `CPU: AMD Ryzen 7 9800X3D 8-Core Processor -` which isn't perfect, since it's suffixed by `- Speed` it's capturing a trailing hyphen, but I'm not sure what the best general fix for that is.

**Comment by hdrie** [comment]
Good catch! The Log.txt syntax has probably changed with a recent update.
The regex will probably need ongoing maintenance as LR update their product.

I can't test right now, but your updated regex looks good.
If we assume that the strings "CPU type: " and " - " before "Speed" are static, it could also be modified to

```
$cpuRegex='CPU type: (.+) - Speed.+'
```

Can you try both this regex and the alternative system method and report back?

**Comment by mee** [comment]
tested; your regex works great on my system.

**Comment by hdrie** [comment]
Alright, I've updated the regex (8444fcd5d7f8f97deac038238422e31361a0626c). Should be good for now.
Btw, you are welcome to maintain your own fork of this project and contribute fixes, if need be ;)
