### ISSUE TITLE
Add 'PressAnyKeyToContinue' prompts

### ISSUE THREAD

**Issue by hdrie** [hdrie/xp-benchmark-tool#6]
Add the option to prompt user confirmation in between benchmark runs.
Add a switch variable in the configuration section.

**Comment by colinchaput** [comment]
Working on this!

**Comment by colinchaput** [comment]
Submitted PR :)

**Comment by hdrie** [comment]
Feature added by @colinchaput in [92b734d](https://github.com/hdrie/xp-benchmark-tool/commit/92b734dc5133fa4a68c80c930a5af51042209c01)
